title: "Milind Patil"
email: "milind1995@gmail.com"
description: "AI/ML for Wireless Communications · CSI Sensing · mmWave/6G · Researcher"
url: "https://milindap.github.io"

markdown: kramdown
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _pages

collections:
  teaching:
    output: true
    permalink: /teaching/:path/

author:
  name: "Milind Patil"
  email: "milind1995@gmail.com"
  github: "https://github.com/milindap"
  linkedin: "https://www.linkedin.com/in/milind-patil-97b676122/"
  researchgate: "https://www.researchgate.net/profile/Milind-Patil-30"
  scholar: "https://scholar.google.com/citations?user=YOUR_ID_HERE"


# Navigation
header_pages:
  - index.md
  - _pages/about.md
  - _pages/research.md
  - _pages/publications.md
  - _pages/projects.md
  - _pages/teaching.md
  - _pages/cv.md
  - _pages/contact.md

