# =========================
# Site settings
# =========================
title: "Milind Patil"
description: "AI/ML for Wireless Communications • CSI Sensing • mmWave/6G Research"
url: "https://milindap.github.io"
baseurl: ""

# =========================
# Markdown Engine
# =========================
markdown: kramdown
kramdown:
  input: GFM

# =========================
# Plugins
# =========================
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# =========================
# Navigation pages
# =========================
header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/publications.md
  - _pages/teaching.md
  - _pages/cv.md

# =========================
# Collections
# =========================
collections:
  teaching:
    output: true
    permalink: /teaching/:name/

# =========================
#
