# =========================
# Site settings
# =========================
title: "Milind Patil"
description: "AI/ML for Wireless Communications • CSI Sensing • mmWave/6G Research"
url: "https://milindap.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include folders for GitHub Pages
include:
  - _pages
  - _publications
  - _teaching
  - _files
  - assets

# Navigation
header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/publications.md
  - _pages/teaching.md
  - _pages/cv.md

author:
  name: "Milind Patil"
  email: "milind1995@gmail.com"
  google_scholar: "https://scholar.google.com/citations?user=uVWNe7QAAAAJ"

social_links:
  github: "MilindAP"
  linkedin: "milind-patil"

# Teaching Collection
collections:
  teaching:
    output: true
    permalink: /teaching/:name/
